spring.application.name=jee-2024051104-14

server.port=8080

spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

server.servlet.jsp.init-parameters.development=true

# mysql connetion info
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.126.128:3306/ems_jsp3?characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

# mybatis
mybatis.type-aliases-package=com.vcpf.jee202405110414.entity
mybatis-plus.mapper-locations=classpath*:/mapper/*.xml

# log ??????
logging.level.root=info
logging.level.root.com.vcpf.jee202405110414.dao=debug
