spring.application.name=EmsDemo

server.port=8080

# MVC???????
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

server.servlet.jsp.init-parameters.development=true

# mysql connetion info
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.126.128:3306/ems_jsp3?characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

# mybatis
mybatis.mapper-locations=classpath:com/vcpf/emsdemo/mapper/*.xml
mybatis.type-aliases-package=com.vcpf.emsdemo.entity

# log ??????
logging.level.root=info
logging.level.root.com.zfh.dao=debug
