package com.vcpf.jee202405110418jpa;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableJpaAuditing
public class Jee202405110418JpaApplication {

    public static void main(String[] args) {
        SpringApplication.run(Jee202405110418JpaApplication.class, args);
    }

}
