package com.vcpf.jee202405110414;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.vcpf.jee202405110414.dao")
public class Jee202405110414Application {

    public static void main(String[] args) {
        SpringApplication.run(Jee202405110414Application.class, args);
    }

}
