spring.application.name=jee-2024051104-15

server.port=8080

server.servlet.jsp.init-parameters.development=true

# ????

# ??spring??
# ????????druid????????????druid????????
# ????? 	http://localhost:8080/druid/index.html
# ??????	http://localhost:8080/context_path/druid/index.html
# ????? 	http://localhost:8080/mp/druid/index.html
spring:
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
# ?????????????
url: jdbc:mysql://192.168.126.128:3306/db_mybatisplus?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
username: root
password: 123456
# ?????????????????????????????????????
druid:
# ???????
initialSize: 5
minIdle: 5
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000
validationQuery: SELECT 1
testWhileIdle: true
testOnBorrow: false
testOnReturn: false
# ????
stat-view-servlet:
enabled: true
# ???????????????????????????????
login-username: druid
login-password: 123456
reset-enable: true
url-pattern: "/druid/*"
# allow: 127.0.0.1
filters: stat,wall,slf4j
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
useGlobalDataSourceStat: true
# ??WEB???????????
web-stat-filter:
enabled: true
url-pattern: /*
exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
profile-enable: true
# ??Spring????????????????
aop-patterns: com.zfh.controller.*,com.zfh.service.*,com.zfh.mapper.*
filter:
slf4j:
enabled: true
statement-executable-sql-log-enable: true

logging:
level:
root: info
# ?? SQL
druid.sql.Statement: debug
# ??????
druid.sql.ResultSet: debug
com.zfh.mapper: debug

# WEB ??
server:
port: 8080
servlet:
context-path: /mp
session:
timeout: 60

# ??slq????????????????
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

